name: uts
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  webview_flutter: 4.2.2
  flutter_inappwebview: ^6.0.0-beta.21
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/download.jpeg
    - assets/gambar1.jpeg
    - assets/gambar2.jpeg
    - assets/gambar3.jpeg
    - assets/image.png
    - assets/profile.png

